name: Labeler

on:
  pull_request:

jobs:
  labeler:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/labeler@v5
